# Generated by Django 5.1.7 on 2025-03-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
